#!name=Apple WLOC Location Spoofer
#!desc=Modify the coordinates returned by Apple's network-based location service (WiFi/cell) | Shortcuts (recommended): Set Location https://www.icloud.com/shortcuts/096685588ca14583b01908957219b626 Clear Location https://www.icloud.com/shortcuts/cd0c9258d08f45c1a075ca5fe85a8387 | Picker page: https://wloc-spoofer-en.1169139588.workers.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/paomian1hao/wloc-spoofer-en

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/paomian1hao/wloc-spoofer-en/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/paomian1hao/wloc-spoofer-en/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
