#!name=Apple WLOC Location Spoofer
#!desc=Modify the coordinates returned by Apple's network-based location service (Shadowrocket) | Shortcuts (recommended): Set Location https://www.icloud.com/shortcuts/d49961b18e51476eaaeb3a1a25c67768 Clear & Restore Location https://www.icloud.com/shortcuts/0352d53ed79849d382f50e9adf050662 | Picker page: https://wloc-spoofer-en.1169139588.workers.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/paomian1hao/wloc-spoofer-en
#!icon=https://raw.githubusercontent.com/paomian1hao/wloc-spoofer-en/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/paomian1hao/wloc-spoofer-en/refs/heads/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/paomian1hao/wloc-spoofer-en/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
